services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`my-app.com`)" # change with your domain
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
    networks:
      - traefik-servicenet

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet
