log:
  level: DEBUG
providers:
  docker:
    exposedByDefault: false
    endpoint: 'tcp://dockerproxy:2375'
    network: traefik-servicenet
api:
  insecure: false
entryPoints:
  web:
    address: ':10080' # will be routed to port 80
    http:
      redirections:
        # redirect entire entrypoint to https
        entryPoint:
          to: ':443'
          scheme: https
  web-secure:
    address: ':10443' # will be routed to port 443
certificatesResolvers:
  le:
    acme:
      # uncomment next line for testing purpose
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: your@email.com # replace with your email address
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 10
